CREATE TABLE "identity"
(
    ID INT NOT NULL PRIMARY KEY ,
    USERID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CHOSENALGORITHM VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL
)
