CREATE SEQUENCE identity_seq;
CREATE TABLE "identity"
(
    ID BIGINT NOT NULL DEFAULT nextval('identity_seq'),
    USERID UUID NOT NULL,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    CHOSENALGORITHM TEXT NOT NULL,
    SALT UUID NOT NULL,
    PRIMARY KEY (ID)
)
