CREATE SEQUENCE password_seq;
CREATE TABLE "password"
(
    ID BIGINT NOT NULL DEFAULT nextval('password_seq'),
    USERID UUID NOT NULL,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    URL TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID)
)
